version: "3.9"

services:
  web:
    depends_on:
      - postgres_db
    build:
      context: ./web
      dockerfile: Dockerfile
    image: django-k8s:1.0
    env_file:
      - web/.env
    environment:
      - PORT=8080
    ports:
      - "8000:8080"
    command:
      - sh
      - -c
      - |
        chmod +x /app/migrate.sh
        sh /app/migrate.sh
        sh /app/entrypoint.sh

  postgres_db:
    image: postgres
    restart: always
    env_file:
      - web/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -h postgres_db
      interval: 1s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
    driver: local
